### Home Route
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjY3NjEzODQsImV4cCI6MTYyNjc2NDk4NCwiYXVkIjoiNjBmNjY2OTBjYTJlMGE3N2IzYmQyOTYzIiwiaXNzIjoia29rYXVuZy5jb20ifQ.6OaPWR0yPbIgAxRhLckzDIOPVqnFLBxW2H2w3MFLhSY

### Error
GET  http://localhost:3000/abc_xyz

### Register
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "user3@mail.com",
    "password": "P@ssword"
}

### Login
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user1@mail.com",
    "password": "P@ssword"
}

### Refresh token
POST  http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjY3NjEzODQsImV4cCI6MTY1ODMxODk4NCwiYXVkIjoiNjBmNjY2OTBjYTJlMGE3N2IzYmQyOTYzIiwiaXNzIjoia29rYXVuZy5jb20ifQ.Oq30TffF4g-EM3w1WUGO7E6Ui45seitMEEHj-QFuJRw"
}

### Logout
DELETE  http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjY3NjEzODQsImV4cCI6MTY1ODMxODk4NCwiYXVkIjoiNjBmNjY2OTBjYTJlMGE3N2IzYmQyOTYzIiwiaXNzIjoia29rYXVuZy5jb20ifQ.Oq30TffF4g-EM3w1WUGO7E6Ui45seitMEEHj-QFuJRw"
}
